# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fenix.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/fenix.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11proto/fenix.proto\"\xdf\x02\n\x0e\x41uthorizedUser\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12/\n\x08settings\x18\x04 \x03(\x0b\x32\x1d.AuthorizedUser.SettingsEntry\x12\r\n\x05token\x18\x05 \x01(\t\x12\x14\n\x0cusernameHash\x18\x06 \x01(\x03\x12\x11\n\tcreatedAt\x18\x07 \x01(\t\x12\x10\n\x08verified\x18\x08 \x01(\x08\x12-\n\x07servers\x18\t \x03(\x0b\x32\x1c.AuthorizedUser.ServersEntry\x1a=\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.UserSetting:\x02\x38\x01\x1a\x37\n\x0cServersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Server:\x02\x38\x01\"X\n\rReactionAdded\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tmessageID\x18\x02 \x01(\x03\x12\x19\n\x11numberOfReactions\x18\x03 \x01(\x05\x12\r\n\x05\x65moji\x18\x04 \x01(\t\"\x87\x01\n\x06Server\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08serverID\x18\x02 \x01(\x03\x12\x1a\n\x08\x63hannels\x18\x03 \x03(\x0b\x32\x08.Channel\x12\x19\n\x05users\x18\x04 \x03(\x0b\x32\n.BasicUser\x12\x14\n\x0cserverAvatar\x18\x05 \x01(\t\x12\x12\n\nserverName\x18\x06 \x01(\t\"S\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tchannelID\x18\x02 \x01(\x03\x12\x13\n\x0b\x63hannelName\x18\x03 \x01(\t\x12\x14\n\x0c\x63\x61tegoryName\x18\x04 \x01(\t\"U\n\tBasicUser\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06userID\x18\x02 \x01(\x03\x12\x0e\n\x06roleID\x18\x03 \x01(\x03\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x0c\n\x04nick\x18\x05 \x01(\t\"*\n\x0bUserSetting\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07setting\x18\x02 \x01(\x08\x62\x06proto3'
)




_AUTHORIZEDUSER_SETTINGSENTRY = _descriptor.Descriptor(
  name='SettingsEntry',
  full_name='AuthorizedUser.SettingsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AuthorizedUser.SettingsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AuthorizedUser.SettingsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=316,
)

_AUTHORIZEDUSER_SERVERSENTRY = _descriptor.Descriptor(
  name='ServersEntry',
  full_name='AuthorizedUser.ServersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AuthorizedUser.ServersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AuthorizedUser.ServersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=373,
)

_AUTHORIZEDUSER = _descriptor.Descriptor(
  name='AuthorizedUser',
  full_name='AuthorizedUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AuthorizedUser.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='AuthorizedUser.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='AuthorizedUser.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settings', full_name='AuthorizedUser.settings', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='AuthorizedUser.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usernameHash', full_name='AuthorizedUser.usernameHash', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdAt', full_name='AuthorizedUser.createdAt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verified', full_name='AuthorizedUser.verified', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servers', full_name='AuthorizedUser.servers', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUTHORIZEDUSER_SETTINGSENTRY, _AUTHORIZEDUSER_SERVERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=373,
)


_REACTIONADDED = _descriptor.Descriptor(
  name='ReactionAdded',
  full_name='ReactionAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReactionAdded.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageID', full_name='ReactionAdded.messageID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberOfReactions', full_name='ReactionAdded.numberOfReactions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emoji', full_name='ReactionAdded.emoji', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=463,
)


_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Server.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverID', full_name='Server.serverID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='Server.channels', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='Server.users', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverAvatar', full_name='Server.serverAvatar', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverName', full_name='Server.serverName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=601,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Channel.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelID', full_name='Channel.channelID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channelName', full_name='Channel.channelName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categoryName', full_name='Channel.categoryName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=603,
  serialized_end=686,
)


_BASICUSER = _descriptor.Descriptor(
  name='BasicUser',
  full_name='BasicUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BasicUser.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userID', full_name='BasicUser.userID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roleID', full_name='BasicUser.roleID', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='BasicUser.avatar', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nick', full_name='BasicUser.nick', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=773,
)


_USERSETTING = _descriptor.Descriptor(
  name='UserSetting',
  full_name='UserSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserSetting.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='UserSetting.setting', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=775,
  serialized_end=817,
)

_AUTHORIZEDUSER_SETTINGSENTRY.fields_by_name['value'].message_type = _USERSETTING
_AUTHORIZEDUSER_SETTINGSENTRY.containing_type = _AUTHORIZEDUSER
_AUTHORIZEDUSER_SERVERSENTRY.fields_by_name['value'].message_type = _SERVER
_AUTHORIZEDUSER_SERVERSENTRY.containing_type = _AUTHORIZEDUSER
_AUTHORIZEDUSER.fields_by_name['settings'].message_type = _AUTHORIZEDUSER_SETTINGSENTRY
_AUTHORIZEDUSER.fields_by_name['servers'].message_type = _AUTHORIZEDUSER_SERVERSENTRY
_SERVER.fields_by_name['channels'].message_type = _CHANNEL
_SERVER.fields_by_name['users'].message_type = _BASICUSER
DESCRIPTOR.message_types_by_name['AuthorizedUser'] = _AUTHORIZEDUSER
DESCRIPTOR.message_types_by_name['ReactionAdded'] = _REACTIONADDED
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['BasicUser'] = _BASICUSER
DESCRIPTOR.message_types_by_name['UserSetting'] = _USERSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthorizedUser = _reflection.GeneratedProtocolMessageType('AuthorizedUser', (_message.Message,), {

  'SettingsEntry' : _reflection.GeneratedProtocolMessageType('SettingsEntry', (_message.Message,), {
    'DESCRIPTOR' : _AUTHORIZEDUSER_SETTINGSENTRY,
    '__module__' : 'proto.fenix_pb2'
    # @@protoc_insertion_point(class_scope:AuthorizedUser.SettingsEntry)
    })
  ,

  'ServersEntry' : _reflection.GeneratedProtocolMessageType('ServersEntry', (_message.Message,), {
    'DESCRIPTOR' : _AUTHORIZEDUSER_SERVERSENTRY,
    '__module__' : 'proto.fenix_pb2'
    # @@protoc_insertion_point(class_scope:AuthorizedUser.ServersEntry)
    })
  ,
  'DESCRIPTOR' : _AUTHORIZEDUSER,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:AuthorizedUser)
  })
_sym_db.RegisterMessage(AuthorizedUser)
_sym_db.RegisterMessage(AuthorizedUser.SettingsEntry)
_sym_db.RegisterMessage(AuthorizedUser.ServersEntry)

ReactionAdded = _reflection.GeneratedProtocolMessageType('ReactionAdded', (_message.Message,), {
  'DESCRIPTOR' : _REACTIONADDED,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:ReactionAdded)
  })
_sym_db.RegisterMessage(ReactionAdded)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), {
  'DESCRIPTOR' : _SERVER,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:Server)
  })
_sym_db.RegisterMessage(Server)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:Channel)
  })
_sym_db.RegisterMessage(Channel)

BasicUser = _reflection.GeneratedProtocolMessageType('BasicUser', (_message.Message,), {
  'DESCRIPTOR' : _BASICUSER,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:BasicUser)
  })
_sym_db.RegisterMessage(BasicUser)

UserSetting = _reflection.GeneratedProtocolMessageType('UserSetting', (_message.Message,), {
  'DESCRIPTOR' : _USERSETTING,
  '__module__' : 'proto.fenix_pb2'
  # @@protoc_insertion_point(class_scope:UserSetting)
  })
_sym_db.RegisterMessage(UserSetting)


_AUTHORIZEDUSER_SETTINGSENTRY._options = None
_AUTHORIZEDUSER_SERVERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
