# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12proto/server.proto\"\x1e\n\x10RequestUserCount\x12\n\n\x02id\x18\x01 \x01(\x03\",\n\x0fReturnUserCount\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x62\x06proto3'
)




_REQUESTUSERCOUNT = _descriptor.Descriptor(
  name='RequestUserCount',
  full_name='RequestUserCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RequestUserCount.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_RETURNUSERCOUNT = _descriptor.Descriptor(
  name='ReturnUserCount',
  full_name='ReturnUserCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReturnUserCount.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='ReturnUserCount.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['RequestUserCount'] = _REQUESTUSERCOUNT
DESCRIPTOR.message_types_by_name['ReturnUserCount'] = _RETURNUSERCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestUserCount = _reflection.GeneratedProtocolMessageType('RequestUserCount', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUSERCOUNT,
  '__module__' : 'proto.server_pb2'
  # @@protoc_insertion_point(class_scope:RequestUserCount)
  })
_sym_db.RegisterMessage(RequestUserCount)

ReturnUserCount = _reflection.GeneratedProtocolMessageType('ReturnUserCount', (_message.Message,), {
  'DESCRIPTOR' : _RETURNUSERCOUNT,
  '__module__' : 'proto.server_pb2'
  # @@protoc_insertion_point(class_scope:ReturnUserCount)
  })
_sym_db.RegisterMessage(ReturnUserCount)


# @@protoc_insertion_point(module_scope)
